# file: deploy.yml
- hosts: app-servers
  user: maverick

  tasks:
  - name: create project dir if not exist
    file:
      path: /Users/maverick/dev/ansible
      state: directory

  - name: clone github repo
    git:
      repo: git@github.com:i-maverick/ansible.git
      version: master
      dest: /Users/maverick/dev/ansible
    register: ansible_repo

  - name: restart service
    service:
      name: network
      state: restarted
    debug: msg="service restarted"
    when: ansible_repo.changed
