# file: deploy.yml
# usage: ansible-playbook -i hosts deploy.yml --extra-vars "version=master"

- hosts: app-servers
  vars:
    user: maverick
    destination: /home/{{ user }}/Development/ansible
  user: '{{ user }}'

  tasks:
  - name: create project dir if not exist
    file:
      path: '{{ destination }}'
      state: directory

  - name: clone github repo
    git:
      repo: git@github.com:i-maverick/ansible.git
      version: '{{ version }}'
      dest: '{{ destination }}'
      force: yes
    notify:
    - restart service

  handlers:
  - name: restart service
    become: yes
    service:
      name: cron
      state: restarted
    notify:
    - service restarted

  - name: service restarted
    debug: msg='service restarted'
