# file: deploy.yml
# usage: ansible-playbook -i hosts deploy.yml --extra-vars "version=master"

- hosts: local
  vars:
    user: bi
    destination: /home/{{ user }}/Development/ansible
  user: '{{ user }}'

  tasks:
  - name: create project dir if not exist
    file:
      path: '{{ destination }}'
      state: directory

  - name: clone github repo
    git:
      repo: git@github.com:i-maverick/ansible.git
      version: '{{ version }}'
      dest: '{{ destination }}'
      force: yes
    register: ansible_repo

  - name: restart service
    service:
      name: cron
      state: restarted
    when: ansible_repo.changed

  - debug: msg="service restarted!"
    when: ansible_repo.changed
