# file: deploy.yml

- hosts: local-servers
  tasks:
  - ping:

- hosts: app-servers
  user: maverick

  tasks:
  - name: ping remote host
    ping:

  - name: create project dir if not exist
    file:
      path: /Users/maverick/dev/ansible
      state: directory

  - name: clone github repo
    git:
      repo: git@github.com:i-maverick/ansible.git
      version: master
      dest: /Users/maverick/dev/ansible
    register: ansible_repo

  - name: on change
    debug:
      msg: "Repo was changed"
    when: ansible_repo.changed

  - name: restart service
    service:
      name: network
      state: restarted
    when: ansible_repo.changed
