# file: keys.yml

- hosts: app-servers
  user: ansible
  tasks:
  - name: Set up authorized_keys for the ansible user
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"
