# file: keys.yml

- hosts: local
  user: bi
  tasks:
  - name: Set up authorized_keys for the ansible user
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/home/bi/.ssh/id_rsa.pub') }}"
